kind: pipeline
name: dev
type: kubernetes
dns_config:
  options:
    - name: ndots
      value: '1'
steps:
  - name: build
    image: plugins/docker
    settings:
      username: k3env
      password:
        from_secret: DOCKER_PASSWORD
      repo: k3env/vcl-backend
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
trigger:
  event:
    - push
    - promote
    - custom
---
kind: pipeline
name: release
type: kubernetes
dns_config:
  options:
    - name: ndots
      value: '1'
steps:
  - name: build
    image: plugins/docker
    settings:
      username: k3env
      password:
        from_secret: DOCKER_PASSWORD
      repo: k3env/vcl-backend
      tags:
        - ${DRONE_TAG}
        - stable
trigger:
  event:
    - tag
