kind: pipeline
name: default
type: docker
steps:
  - name: build
    image: plugins/docker
    settings:
      username: k3env
      password:
        from_secret: DOCKER_PASSWORD
      repo: k3env/vcl-backend
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
trigger:
  event:
    - push
    - pull_request
---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy
    image: loq9/drone-nomad
    settings:
      addr: https://nomad.k3env.site
      template: deploy/jobspec.nomad
      token:
        from_secret: NOMAD_TOKEN
trigger:
  event:
    - promote
  target:
    - production
